### ISSUE TITLE
Player moving without input

### ISSUE THREAD

**Issue by JaumeMontagut** [gamificalostudio/Tankerfield#37]
Build: 0.2
If you move the left joystick slightly down and let it go quickly, the player will start moving down.

**Comment by JaumeMontagut** [comment]
Observation: Only hapens in some controllers. It can be a problem with the dead zone of each controller. I suggest modifying it and test it again.

**Comment by AitorVelez** [comment]
Dead zone has been changed to 2500. This does not happen anymore.Fixed in 0.2.5
