### ISSUE TITLE
Split screen + shoot with mouse

### ISSUE THREAD

**Issue by jorgegh2** [gamificalostudio/Tankerfield#68]
**Describe the bug**
when shoot with mouse, all tanks take the direction of the first tank only because only take the first camera.
**To Reproduce**
shoot with mouse and with split screen on.

**Expected behavior**
each tank calculate the direction of the bullet with his own camera.

**Screenshots**
![image](https://user-images.githubusercontent.com/36292074/55676353-fd264c00-58d3-11e9-8805-9c99b54dce70.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JaumeMontagut** [comment]
Not important enogh to dedicate the time to look into it.
The game is meant to be played on controlled and only use mouse for debugging purposes.
Mouse works fine for player one so debugging is okay.
