### ISSUE TITLE
Store non-enemy objects in another list

### ISSUE THREAD

**Issue by vsRushy** [gamificalostudio/Tankerfield#86]
This would make the wave system easier to make.

**Comment by vsRushy** [comment]
The ideal thing would be to have only a list for enemies.

**Comment by JaumeMontagut** [comment]
Maybe we could create another method in the object manager called "CreateEnemy()" which only creates enemies and then pushes them back to the enemy list.
However, I don't see why we need to have them separated from the objects list, at the end of the day we want them to do their Update() or Draw() in the same way as any other object.
If we need a list to interate through them to see if they are dead or something similar we could have a separate list and assign them to that list after creating the object normally.
